import { createHash } from "node:crypto";

import { BSON, type Document } from "mongodb";

export interface FingerprintOptions {
  /**
   * The `_id` value known by the caller to have been generated by MongoDB.
   * `_id` is retained unless this provenance is supplied and the value matches.
   */
  generatedId?: unknown;
}

export interface DocumentFingerprint {
  fields: Record<string, string>;
  fingerprint: string;
  hash: string;
}

// The readable `fingerprint` signature is unbounded in length and made of
// model-authored field names, so it cannot go into a telemetry record: those
// must stay under PIPE_BUF to keep concurrent appends atomic. `hash` is the
// same shape as a fixed 16 hex characters, so the pilot's JSONL stream and a
// post-hoc `inspect` over MongoDB cluster documents by the *same* key -- which
// only holds because both come from this one function.
export function hashFingerprint(signature: string): string {
  return createHash("sha256").update(signature).digest("hex").slice(0, 16);
}

interface TypeDescription {
  paths: Map<string, Set<string>>;
  signature: string;
}

function scalarType(value: unknown): string {
  if (value === null) return "null";
  if (value instanceof Date) return "date";

  if (typeof value === "object") {
    const bsonName = (value as { _bsontype?: unknown })._bsontype;
    if (typeof bsonName === "string") return bsonName.toLowerCase();
    return "object";
  }

  return typeof value;
}

function addPath(
  paths: Map<string, Set<string>>,
  path: string,
  signature: string,
): void {
  const signatures = paths.get(path) ?? new Set<string>();
  signatures.add(signature);
  paths.set(path, signatures);
}

function mergePaths(
  target: Map<string, Set<string>>,
  source: Map<string, Set<string>>,
): void {
  for (const [path, signatures] of source) {
    for (const signature of signatures) addPath(target, path, signature);
  }
}

function union(signatures: Iterable<string>): string {
  const sorted = [...new Set(signatures)].sort();
  return sorted.length === 1 ? sorted[0] : `union<${sorted.join("|")}>`;
}

function describeValue(value: unknown, path: string): TypeDescription {
  if (Array.isArray(value)) {
    const paths = new Map<string, Set<string>>();
    if (value.length === 0) {
      addPath(paths, path, "array<empty>");
      return { paths, signature: "array<empty>" };
    }

    const elements = value.map((element) =>
      describeValue(element, `${path}[]`),
    );
    const elementType = union(elements.map(({ signature }) => signature));
    const signature = `array<${elementType}>`;
    addPath(paths, path, signature);
    for (const element of elements) mergePaths(paths, element.paths);
    return { paths, signature };
  }

  if (value !== null && typeof value === "object") {
    const bsonName = (value as { _bsontype?: unknown })._bsontype;
    if (typeof bsonName === "string" || value instanceof Date) {
      const signature = scalarType(value);
      return {
        paths: new Map([[path, new Set([signature])]]),
        signature,
      };
    }

    const paths = new Map<string, Set<string>>();
    const fields: string[] = [];
    addPath(paths, path, "object");
    for (const key of Object.keys(value).sort()) {
      const child = describeValue(
        (value as Record<string, unknown>)[key],
        `${path}.${key}`,
      );
      fields.push(`${JSON.stringify(key)}:${child.signature}`);
      mergePaths(paths, child.paths);
    }
    return {
      paths,
      signature: `object{${fields.join(",")}}`,
    };
  }

  const signature = scalarType(value);
  return {
    paths: new Map([[path, new Set([signature])]]),
    signature,
  };
}

function sameBsonValue(left: unknown, right: unknown): boolean {
  if (Object.is(left, right)) return true;
  try {
    return (
      BSON.EJSON.stringify(left, { relaxed: false }) ===
      BSON.EJSON.stringify(right, { relaxed: false })
    );
  } catch {
    return false;
  }
}

export function fingerprintDocument(
  document: Document,
  options: FingerprintOptions = {},
): DocumentFingerprint {
  const paths = new Map<string, Set<string>>();
  const rootFields: string[] = [];
  const hasGeneratedId = Object.hasOwn(options, "generatedId");

  for (const key of Object.keys(document).sort()) {
    if (
      key === "_id" &&
      hasGeneratedId &&
      sameBsonValue(document[key], options.generatedId)
    ) {
      continue;
    }
    const description = describeValue(document[key], key);
    rootFields.push(`${JSON.stringify(key)}:${description.signature}`);
    mergePaths(paths, description.paths);
  }

  const fields = Object.fromEntries(
    [...paths]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([path, signatures]) => [path, union(signatures)]),
  );

  const fingerprint = `document{${rootFields.join(",")}}`;
  return { fields, fingerprint, hash: hashFingerprint(fingerprint) };
}
